# rt.movie_info.tsv analysis

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("Data/rt.movie_info.tsv", delimiter="\t")
data.head(10)

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,"Oct 9, 1971","Sep 25, 2001",NaN,NaN,104 minutes,NaN
1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012","Jan 1, 2013",$,"600,000",108 minutes,Entertainment One
2,5,Illeana Douglas delivers a superb performance ...,R,Drama|Musical and Performing Arts,Allison Anders,Allison Anders,"Sep 13, 1996","Apr 18, 2000",NaN,NaN,116 minutes,NaN
3,6,Michael Douglas runs afoul of a treacherous su...,R,Drama|Mystery and Suspense,Barry Levinson,Paul Attanasio|Michael Crichton,"Dec 9, 1994","Aug 27, 1997",NaN,NaN,128 minutes,NaN
4,7,NaN,NR,Drama|Romance,Rodney Bennett,Giles Cooper,NaN,NaN,NaN,NaN,200 minutes,NaN
5,8,The year is 1942. As the Allies unite overseas...,PG,Drama|Kids and Family,Jay Russell,Gail Gilchriest,"Mar 3, 2000","Jul 11, 2000",NaN,NaN,95 minutes,Warner Bros. Pictures
6,10,Some cast and crew from NBC's highly acclaimed...,PG-13,Comedy,Jake Kasdan,Mike White,"Jan 11, 2002","Jun 18, 2002",$,"41,032,915",82 minutes,Paramount Pictures
7,13,"Stewart Kane, an Irishman living in the Austra...",R,Drama,Ray Lawrence,Raymond Carver|Beatrix Christian,"Apr 27, 2006","Oct 2, 2007",$,"224,114",123 minutes,Sony Pictures Classics
8,14,"""Love Ranch"" is a bittersweet love story that ...",R,Drama,Taylor Hackford,Mark Jacobson,"Jun 30, 2010","Nov 9, 2010",$,"134,904",117 minutes,NaN
9,15,When a diamond expedition in the Congo is lost...,PG-13,Action and Adventure|Mystery and Suspense|Scie...,Frank Marshall,John Patrick Shanley,"Jun 9, 1995","Jul 27, 1999",NaN,NaN,108 minutes,NaN

In [3]:
# data shape

data.shape

(1560, 12)

In [4]:
# data info
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1560 entries, 0 to 1559
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1560 non-null   int64
 1   synopsis      1498 non-null   object
 2   rating        1557 non-null   object
 3   genre         1552 non-null   object
 4   director      1361 non-null   object
 5   writer        1111 non-null   object
 6   theater_date  1201 non-null   object
 7   dvd_date      1201 non-null   object
 8   currency      340 non-null    object
 9   box_office    340 non-null    object
 10  runtime       1530 non-null   object
 11  studio        494 non-null    object
dtypes: int64(1), object(11)
memory usage: 146.4+ KB

In [9]:
data['currency'].value_counts()

currency
$    340
Name: count, dtype: int64

In [10]:
data['rating'].value_counts()

rating
R        521
NR       503
PG       240
PG-13    235
G         57
NC17       1
Name: count, dtype: int64

In [13]:
data[data['rating'] == 'NC17']

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
1215,1567,Lust is in the air on Harford Road and Sylvia ...,NC17,Comedy,John Waters,John Waters,"Sep 24, 2004","Jun 14, 2005",$,"1,260,219",89 minutes,New Line Cinema

In [14]:
data['genre'].value_counts()

genre
Drama                                                                                     151
Comedy                                                                                    110
Comedy|Drama                                                                               80
Drama|Mystery and Suspense                                                                 67
Art House and International|Drama                                                          62
                                                                                         ...
Art House and International|Drama|Sports and Fitness                                        1
Comedy|Documentary|Musical and Performing Arts|Special Interest                             1
Comedy|Cult Movies|Mystery and Suspense|Science Fiction and Fantasy                         1
Action and Adventure|Art House and International|Mystery and Suspense|Special Interest      1
Comedy|Drama|Kids and Family|Sports and Fitness                                             1
Name: count, Length: 299, dtype: int64

In [15]:
data1 = data.sample(n = 20, random_state=1)
data1

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
1279,1651,The action in this film revolves largely aroun...,R,Art House and International|Drama,Atom Egoyan,Atom Egoyan,"May 16, 1994","Nov 16, 1999",NaN,NaN,104 minutes,NaN
1317,1702,A film about the late Oregon running legend St...,PG-13,Documentary|Drama,Robert Towne,Kenny Moore|Robert Towne,"Sep 11, 1998","Feb 16, 1999",NaN,NaN,119 minutes,NaN
177,234,"After losing his crew in a fatal crash, legend...",PG-13,Action and Adventure|Drama,NaN,Kelsie Kullman,"Sep 29, 2006","Jan 23, 2007",$,"54,983,983",15 minutes,Buena Vista Pictures
409,534,This is the true story of Rocky Dennis (Eric S...,R,Drama,Peter Bogdanovich,Anna Hamilton Phelan|Peter Bogdanovich,"Mar 8, 1985","Oct 10, 2000",NaN,NaN,120 minutes,NaN
447,586,Tali Shemesh's understated seriocomic document...,NR,Documentary|Special Interest,NaN,NaN,NaN,NaN,NaN,NaN,90 minutes,NaN
480,627,The Kid Stays in the Picture director Brett Mo...,R,Animation|Documentary|Drama,Brett Morgen,Brett Morgen,"Feb 27, 2008","Aug 26, 2008",NaN,NaN,100 minutes,NaN
1424,1837,"""Becoming Jane,"" is the story of the great, un...",PG,Drama|Romance,Julian Jarrold,Sarah Williams|Kevin Hood,"Aug 3, 2007","Feb 12, 2008",$,"18,602,895",120 minutes,Miramax Films
521,683,Sean Connery appears as a British publisher wh...,R,Action and Adventure|Drama|Mystery and Suspense,Fred Schepisi,Tom Stoppard,"Dec 19, 1990","Dec 26, 2001",NaN,NaN,122 minutes,NaN
1425,1839,The musicians of the Buena Vista Social Club e...,PG,Documentary,Lucy Walker,NaN,"May 26, 2017","Sep 12, 2017",$,"118,253",111 minutes,NaN
535,697,Hungarian filmmaker Bela Tarr began his career...,NR,Art House and International|Drama,Bela Tarr,NaN,"Feb 16, 1988","Apr 25, 2006",NaN,NaN,116 minutes,NaN
987,1280,Two teenage girls embark on wild adventure aft...,NR,Action and Adventure|Comedy,Chris Riedell|Nick Riedell,Daniel Kinno,NaN,NaN,NaN,NaN,92 minutes,NaN
1163,1496,"In the years before World War II, a Japanese c...",PG-13,Drama|Romance,Rob Marshall,Robin Swicord,"Dec 16, 2005","Mar 28, 2006",$,"57,000,000",105 minutes,Sony Pictures
1116,1441,A Christmas Eve in a very blended family turns...,NR,Comedy,Olivier Doran,NaN,NaN,NaN,NaN,NaN,85 minutes,NaN
382,495,A U.S. senator who is planning an upcoming ele...,PG,Comedy|Drama,NaN,Miguel Tejada-Flores|Tim Metcalfe|Richard Martini,NaN,NaN,NaN,NaN,98 minutes,NaN
1358,1753,Carmel Myers' co-star in this amusing farce is...,NR,Comedy,Paul Powell,NaN,NaN,NaN,NaN,NaN,5 minutes,NaN
1131,1459,From executive producer Angelina Jolie Pitt co...,NR,Documentary|Drama,Zeresenay Berhane Mehari,Zeresenay Berhane Mehari,NaN,NaN,NaN,NaN,96 minutes,Truth Aid
978,1270,NaN,NR,Art House and International|Drama,Xie Jin,Yanzhou Lu,NaN,NaN,NaN,NaN,120 minutes,NaN
1400,1805,The give and take between the members of a str...,NR,Drama,Joe Hisaishi,NaN,NaN,NaN,NaN,NaN,112 minutes,NaN
60,75,Nicolas Cage headlines this high-octane thrill...,R,Action and Adventure|Mystery and Suspense,Patrick Lussier,NaN,"Feb 25, 2011","May 31, 2011",$,"10,706,786",107 minutes,Summit Entertainment
729,936,A teen-aged girl nearly comes unglued after he...,PG-13,Drama|Romance,Craig Bolotin,Craig Bolotin,"Jun 1, 1993","Feb 9, 1994",NaN,NaN,89 minutes,NaN